---
- name: Setup Waartaa webserver
  hosts: webservers
  roles:
    - common
    - nodejs
    - nginx

- name: Setup Waartaa dbserver
  hosts: dbservers
  roles:
    - common
    - mongo

- name: Bundle waartaa
  hosts: localhost
  connection: local
  roles:
    - bundle_waartaa

- name: Deploy app
  hosts: webservers
  roles:
    - app_deploy

