---
  - name: Configure package management service (YUM)
    sudo: yes
    template: src=mongodb.repo.j2 dest=/etc/yum.repos.d/mongodb.repo owner=root group=root


  - name: Install MongoDB packages
    sudo: yes
    yum: name={{ item }}
    with_items:
      - mongodb
      - mongodb-server

  - name: update the MongoDB conf file
    sudo: yes 
    template: src={{ mongo_confTemplate }} dest={{ mongo_confFile }} owner=root group=root

  - name: ensure MongoDB is running
    sudo: yes
    service: name=mongod state=started enabled=yes

  - name: Create the file to initialize the mongod replica set
    template: src=repset_init.j2 dest=/tmp/repset_init.js

  - name: Pause for a while
    pause: seconds=5

  - name: Initialize the replication set
    shell: /usr/bin/mongo --port 27017 /tmp/repset_init.js

